# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.mainClockLabel = QtWidgets.QLabel(Dialog)
        self.mainClockLabel.setObjectName("mainClockLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mainClockLabel)
        self.controlTypeLabel = QtWidgets.QLabel(Dialog)
        self.controlTypeLabel.setObjectName("controlTypeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.controlTypeLabel)
        self.controlTypeComboBox = QtWidgets.QComboBox(Dialog)
        self.controlTypeComboBox.setObjectName("controlTypeComboBox")
        self.controlTypeComboBox.addItem("")
        self.controlTypeComboBox.addItem("")
        self.controlTypeComboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.controlTypeComboBox)
        self.synchronizeControlLabel = QtWidgets.QLabel(Dialog)
        self.synchronizeControlLabel.setObjectName("synchronizeControlLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.synchronizeControlLabel)
        self.synchronizeControlCheckBox = QtWidgets.QCheckBox(Dialog)
        self.synchronizeControlCheckBox.setObjectName("synchronizeControlCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.synchronizeControlCheckBox)
        self.usePLLLabel = QtWidgets.QLabel(Dialog)
        self.usePLLLabel.setObjectName("usePLLLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.usePLLLabel)
        self.usePLLCheckBox = QtWidgets.QCheckBox(Dialog)
        self.usePLLCheckBox.setObjectName("usePLLCheckBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.usePLLCheckBox)
        self.useDividerLabel = QtWidgets.QLabel(Dialog)
        self.useDividerLabel.setObjectName("useDividerLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.useDividerLabel)
        self.useDividerCheckBox = QtWidgets.QCheckBox(Dialog)
        self.useDividerCheckBox.setObjectName("useDividerCheckBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.useDividerCheckBox)
        self.generateByFreqLabel = QtWidgets.QLabel(Dialog)
        self.generateByFreqLabel.setObjectName("generateByFreqLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.generateByFreqLabel)
        self.generateByFreqCheckBox = QtWidgets.QCheckBox(Dialog)
        self.generateByFreqCheckBox.setObjectName("generateByFreqCheckBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.generateByFreqCheckBox)
        self.assignAllFreqLabel = QtWidgets.QLabel(Dialog)
        self.assignAllFreqLabel.setObjectName("assignAllFreqLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.assignAllFreqLabel)
        self.assignAllFreqCheckBox = QtWidgets.QCheckBox(Dialog)
        self.assignAllFreqCheckBox.setObjectName("assignAllFreqCheckBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.assignAllFreqCheckBox)
        self.freqThresholdLabel = QtWidgets.QLabel(Dialog)
        self.freqThresholdLabel.setObjectName("freqThresholdLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.freqThresholdLabel)
        self.reconfigurationLabel = QtWidgets.QLabel(Dialog)
        self.reconfigurationLabel.setObjectName("reconfigurationLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.reconfigurationLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.freqThresholdSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.freqThresholdSpinBox.setMaximum(1.0)
        self.freqThresholdSpinBox.setSingleStep(0.1)
        self.freqThresholdSpinBox.setObjectName("freqThresholdSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.freqThresholdSpinBox)
        self.mainClockdoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.mainClockdoubleSpinBox.setDecimals(3)
        self.mainClockdoubleSpinBox.setMaximum(100000.0)
        self.mainClockdoubleSpinBox.setObjectName("mainClockdoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mainClockdoubleSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "device"))
        self.nameLabel.setText(_translate("Dialog", "Name"))
        self.mainClockLabel.setText(_translate("Dialog", "Main clock"))
        self.controlTypeLabel.setText(_translate("Dialog", "Control type"))
        self.controlTypeComboBox.setItemText(0, _translate("Dialog", "LEVELS"))
        self.controlTypeComboBox.setItemText(1, _translate("Dialog", "POWER_MODES"))
        self.controlTypeComboBox.setItemText(2, _translate("Dialog", "COMBINED"))
        self.synchronizeControlLabel.setText(_translate("Dialog", "Synchronize control"))
        self.usePLLLabel.setText(_translate("Dialog", "Use PLL"))
        self.useDividerLabel.setText(_translate("Dialog", "Use divider"))
        self.generateByFreqLabel.setText(_translate("Dialog", "Generate by freq"))
        self.assignAllFreqLabel.setText(_translate("Dialog", "Assign all freq"))
        self.freqThresholdLabel.setText(_translate("Dialog", "Freq threshold"))
        self.reconfigurationLabel.setText(_translate("Dialog", "Reconfiguration"))
        self.checkBox_1.setText(_translate("Dialog", "1"))
        self.checkBox_2.setText(_translate("Dialog", "2"))
        self.checkBox_3.setText(_translate("Dialog", "3"))
        self.checkBox_4.setText(_translate("Dialog", "4"))
        self.mainClockdoubleSpinBox.setSuffix(_translate("Dialog", "MHz"))

